In [2]:
import pandas as pd
pd.__version__

'2.0.3'

In [4]:
df = pd.read_csv('yellow_tripdata_2021-01.csv')
df

C:\Users\abrory\AppData\Local\Temp\ipykernel_30548\3115805836.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('yellow_tripdata_2021-01.csv')

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.00,3.00,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.00,0.50,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.00,0.50,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.00,0.50,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.50,0.50,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,NaN,2021-01-25 08:32:04,2021-01-25 08:49:32,NaN,8.80,NaN,NaN,135,82,NaN,21.84,2.75,0.5,0.00,0.0,0.3,25.39,0.0
1369761,NaN,2021-01-25 08:34:00,2021-01-25 09:04:00,NaN,5.86,NaN,NaN,42,161,NaN,26.67,2.75,0.5,0.00,0.0,0.3,30.22,0.0
1369762,NaN,2021-01-25 08:37:00,2021-01-25 08:53:00,NaN,4.45,NaN,NaN,14,106,NaN,25.29,2.75,0.5,0.00,0.0,0.3,28.84,0.0
1369763,NaN,2021-01-25 08:28:00,2021-01-25 08:50:00,NaN,10.04,NaN,NaN,175,216,NaN,28.24,2.75,0.5,0.00,0.0,0.3,31.79,0.0
1369764,NaN,2021-01-25 08:38:00,2021-01-25 08:50:00,NaN,4.93,NaN,NaN,248,168,NaN,20.76,2.75,0.5,0.00,0.0,0.3,24.31,0.0

In [ ]:
from sqlalchemy import create_engine

# create sqlalchemy engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')